//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JardinCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dacudiente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dacudiente()
        {
            this.datosnino = new HashSet<datosnino>();
        }
    
        public string ced { get; set; }
        public string nom_ape { get; set; }
        public string tele { get; set; }
        public string dire { get; set; }
        public string correo { get; set; }
        public string celular { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datosnino> datosnino { get; set; }
    }
}
