//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JardinCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosnino
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datosnino()
        {
            this.regasistencia = new HashSet<regasistencia>();
            this.regnotas = new HashSet<regnotas>();
        }
    
        public string niup { get; set; }
        public string nom_ape { get; set; }
        public string tip_san { get; set; }
        public string ciu_nac { get; set; }
        public string ide_acu { get; set; }
        public Nullable<System.DateTime> fec_nac { get; set; }
        public string dir { get; set; }
        public string tel { get; set; }
        public string eps { get; set; }
    
        public virtual dacudiente dacudiente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regasistencia> regasistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regnotas> regnotas { get; set; }
    }
}
