//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JardinCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmadrecomunitaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dmadrecomunitaria()
        {
            this.regjardines = new HashSet<regjardines>();
        }
    
        public string ced { get; set; }
        public string nom_ape { get; set; }
        public string tel { get; set; }
        public string dir { get; set; }
        public Nullable<System.DateTime> fec_nac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regjardines> regjardines { get; set; }
    }
}
