//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JardinCrud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class senasoft2Entities : DbContext
    {
        public senasoft2Entities()
            : base("name=senasoft2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dacudiente> dacudiente { get; set; }
        public virtual DbSet<datosnino> datosnino { get; set; }
        public virtual DbSet<dmadrecomunitaria> dmadrecomunitaria { get; set; }
        public virtual DbSet<regasistencia> regasistencia { get; set; }
        public virtual DbSet<regjardines> regjardines { get; set; }
        public virtual DbSet<regnotas> regnotas { get; set; }
    }
}
