//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JardinCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class regjardines
    {
        public int ide { get; set; }
        public string ced { get; set; }
        public string nom_jar { get; set; }
        public string dir { get; set; }
        public string esta { get; set; }
    
        public virtual dmadrecomunitaria dmadrecomunitaria { get; set; }
    }
}
