//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JardinCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class regnotas
    {
        public string niup { get; set; }
        public Nullable<System.DateTime> ano_escolar { get; set; }
        public string nivel { get; set; }
        public string nota { get; set; }
        public Nullable<System.DateTime> fec { get; set; }
        public string descrip { get; set; }
        public int idreg { get; set; }
    
        public virtual datosnino datosnino { get; set; }
    }
}
